import { NextResponse } from "next/server";

const project = [
  {
    name: "Better Zxra Bedrock",
    app: "Minecraft Addon",
    version: "1.3.5",
    des: "Enchant your journey",
    longDes:
      "Lets Enchant your journey with this addon\nAdds many features and new mechanics which such as RPG game\nDifficulty the game has been increased, such as a mob has unique ability, new mechanics and many more",
    lang: ["javascript", "json"],
    framework: [],
    href: "/projects/bzb",
    img: "https://raw.githubusercontent.com/CrzxaExe/Better-Zxra-Bedrock/refs/heads/main/Resourcepack/pack_icon.png",
    status: 2,
  },
  {
    name: "Zxra Rest",
    app: "Restfull API",
    version: "1.0.3",
    des: "Connect to Zxra App",
    longDes: "API to connect other app to Zxra",
    lang: ["javascript"],
    framework: ["express"],
    href: "/projects/zxra-rest",
    img: "https://avatars.githubusercontent.com/u/78332709?s=400&u=4aa87c566a5fb68af00b3f830e39200dcfee5529&v=4",
    status: 2,
  },
  {
    name: "Zxra Rest v2",
    app: "Restfull API",
    version: "1.0.0",
    des: "Connect to Zxra App",
    longDes: "API to connect other app to Zxra",
    lang: ["typescript"],
    framework: ["elysia"],
    href: "/projects/zxra-rest-v2",
    img: "https://avatars.githubusercontent.com/u/78332709?s=400&u=4aa87c566a5fb68af00b3f830e39200dcfee5529&v=4",
    status: 2,
  },
  {
    name: "ZxraLib",
    app: "Minecraft Module",
    version: "1.0.9",
    des: "Module for your minecraft addon",
    longDes: "Module to use all Zxra function for useable with many addon",
    lang: ["javascript"],
    framework: [],
    href: "/projects/zxra-lib",
    img: "https://avatars.githubusercontent.com/u/78332709?s=400&u=4aa87c566a5fb68af00b3f830e39200dcfee5529&v=4",
    status: 2,
  },
  {
    name: "Khyro Bot",
    app: "Discord & Whatsapp Bot",
    version: "2.8.0",
    des: "Fun bot",
    longDes: "Bot fun to use and free to use",
    lang: ["javascript"],
    framework: ["@whiskeysocket/baileys"],
    href: "/projects/khyro-bot",
    img: "https://raw.githubusercontent.com/CrzxaExe/CrzxaExe/main/asset/Logo_Khyro.png",
    status: 0,
  },
  {
    name: "MKx",
    app: "Discord & Whatsapp Bot",
    version: "1.6.9",
    des: "Utility bot",
    longDes:
      "Eazier your tasks\nBot with multi functional command(maybe).\nWe will update it everytime",
    lang: ["javascript"],
    framework: ["@whiskeysocket/baileys", "discord.js"],
    href: "/projects/mkx",
    img: "https://cdn.discordapp.com/avatars/992661371923746888/c2a964bb36b1273e8acda8ee293f5f0f.webp?size=4096",
    status: 2,
  },
  {
    name: "ZxraDustry",
    app: "Mindustry Mod",
    version: "0.1.2",
    des: "Zxra Mindustry",
    longDes: "Mod for mindustry",
    lang: ["json"],
    framework: [],
    href: "/projects/mkx",
    img: "https://raw.githubusercontent.com/CrzxaExe/ZxraDustry/main/icon.png",
    status: 1,
  },
  {
    name: "Cz DB",
    app: "Crud",
    version: "1.0.8",
    des: "Zxra Database",
    longDes: "Database for all Zxra app",
    lang: ["javascript"],
    framework: [],
    href: "/projects/cz-db",
    status: 0,
  },
  {
    name: "XDzr",
    app: "React Native App",
    version: "1.0.0",
    des: "Zxra App",
    longDes: "Super Apps from Zxra",
    lang: ["javascript"],
    framework: ["react-native"],
    href: "/projects/xdzr",
    status: 1,
  },
];

export function GET() {
  return NextResponse.json(project);
}
